In [2]:
#imported required modules or packages to clean the data.

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
#to diplay all the columns and 100 rows.
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [4]:
#import orders_table
orders=pd.read_csv(r"D:\Data Analyst\EXCEL\supplychain\FACT_ORDERS.csv")
orders.head()

,order_line_id,order_id,date_id,order_date,customer_id,product_id,category,seller_id,seller_rating,location_id,delivery_person_id,payment_id,campaign_id,fulfillment_id,quantity,unit_price,discount_percentage,tax_percentage,shipping_fee,expected_delivery_date,actual_delivery_date,delivery_rating,order_status,return_flag,refund_amount,return_date,customer_rating,review_text,sentiment_score,delivery_delay_days,delivery_sla_days,gross_amount,discount_amount,tax_amount,net_amount
0,OL00000001,ORD0210788,2026-02-20,2026-02-20,CUST009513,PROD000763,Baby,SELL2379,4.6,LOC0010,DEL01094,PAY005,CAMP0098,FUL002,2,19999,9.66,5.0,86.64,2026-02-22,2026-02-22,4.5,Completed,False,0.0,NaN,4.4,Very soft and baby-friendly material.,0.84,0,2,39998,3863.8068,1999.90,38220.7332
1,OL00000002,ORD0248321,2025-12-02,2025-12-02,CUST003412,PROD000142,Clothing,SELL2964,4.0,LOC0053,DEL01927,PAY004,CAMP0068,FUL003,4,2499,7.04,5.0,215.79,2025-12-03,2025-12-04,3.9,Completed,False,0.0,NaN,4.3,Stitching is neat and well-finished.,0.66,1,1,9996,703.7184,499.80,10007.8716
2,OL00000003,ORD0377603,2025-04-03,2025-04-03,CUST065509,PROD001194,Gaming,SELL2485,3.9,LOC0095,DEL00300,PAY009,CAMP0103,FUL002,5,89999,5.75,5.0,86.64,2025-04-05,2025-04-06,3.9,Completed,False,0.0,NaN,4.6,Highly enjoyable and worth it.,0.44,1,2,449995,25874.7125,22499.75,446706.6775
3,OL00000004,ORD0019414,2025-06-01,2025-06-01,CUST070677,PROD000221,Home,SELL4121,4.0,LOC0038,DEL02152,PAY004,CAMP0001,FUL002,3,1499,0.61,5.0,86.64,2025-06-03,2025-06-03,4.0,Completed,False,0.0,NaN,4.6,Fits perfectly in my space.,0.28,0,2,4497,27.4317,224.85,4781.0583
4,OL00000005,ORD0157859,2025-10-25,2025-10-25,CUST017845,PROD000806,Pets,SELL3183,4.5,LOC0109,DEL03896,PAY012,CAMP0125,FUL003,2,299,4.41,5.0,215.79,2025-10-26,2025-10-26,5.0,Completed,False,0.0,NaN,4.0,Strong and long-lasting material.,0.35,0,1,598,26.3718,29.90,817.3182

In [5]:
#make a copy of original file
od=orders.copy()


- Shape	Number of rows and columns
- Columns	Available fields
- Head	Sample records
- Info	Data types and null values
- Describe	Numeric summary
- Duplicates	Duplicate records
- Missing Values	Null counts
- Unique Values	Category counts

# Data inspection

In [6]:
#check shape of the table to know how many rows and table it have.
od.shape

(790732, 35)

In [7]:
#view the columns in the table.
od.columns

Index(['order_line_id', 'order_id', 'date_id', 'order_date', 'customer_id',
       'product_id', 'category', 'seller_id', 'seller_rating', 'location_id',
       'delivery_person_id', 'payment_id', 'campaign_id', 'fulfillment_id',
       'quantity', 'unit_price', 'discount_percentage', 'tax_percentage',
       'shipping_fee', 'expected_delivery_date', 'actual_delivery_date',
       'delivery_rating', 'order_status', 'return_flag', 'refund_amount',
       'return_date', 'customer_rating', 'review_text', 'sentiment_score',
       'delivery_delay_days', 'delivery_sla_days', 'gross_amount',
       'discount_amount', 'tax_amount', 'net_amount'],
      dtype='object')

In [8]:
#view the sample data how it looks first 5.
od.head()

,order_line_id,order_id,date_id,order_date,customer_id,product_id,category,seller_id,seller_rating,location_id,delivery_person_id,payment_id,campaign_id,fulfillment_id,quantity,unit_price,discount_percentage,tax_percentage,shipping_fee,expected_delivery_date,actual_delivery_date,delivery_rating,order_status,return_flag,refund_amount,return_date,customer_rating,review_text,sentiment_score,delivery_delay_days,delivery_sla_days,gross_amount,discount_amount,tax_amount,net_amount
0,OL00000001,ORD0210788,2026-02-20,2026-02-20,CUST009513,PROD000763,Baby,SELL2379,4.6,LOC0010,DEL01094,PAY005,CAMP0098,FUL002,2,19999,9.66,5.0,86.64,2026-02-22,2026-02-22,4.5,Completed,False,0.0,NaN,4.4,Very soft and baby-friendly material.,0.84,0,2,39998,3863.8068,1999.90,38220.7332
1,OL00000002,ORD0248321,2025-12-02,2025-12-02,CUST003412,PROD000142,Clothing,SELL2964,4.0,LOC0053,DEL01927,PAY004,CAMP0068,FUL003,4,2499,7.04,5.0,215.79,2025-12-03,2025-12-04,3.9,Completed,False,0.0,NaN,4.3,Stitching is neat and well-finished.,0.66,1,1,9996,703.7184,499.80,10007.8716
2,OL00000003,ORD0377603,2025-04-03,2025-04-03,CUST065509,PROD001194,Gaming,SELL2485,3.9,LOC0095,DEL00300,PAY009,CAMP0103,FUL002,5,89999,5.75,5.0,86.64,2025-04-05,2025-04-06,3.9,Completed,False,0.0,NaN,4.6,Highly enjoyable and worth it.,0.44,1,2,449995,25874.7125,22499.75,446706.6775
3,OL00000004,ORD0019414,2025-06-01,2025-06-01,CUST070677,PROD000221,Home,SELL4121,4.0,LOC0038,DEL02152,PAY004,CAMP0001,FUL002,3,1499,0.61,5.0,86.64,2025-06-03,2025-06-03,4.0,Completed,False,0.0,NaN,4.6,Fits perfectly in my space.,0.28,0,2,4497,27.4317,224.85,4781.0583
4,OL00000005,ORD0157859,2025-10-25,2025-10-25,CUST017845,PROD000806,Pets,SELL3183,4.5,LOC0109,DEL03896,PAY012,CAMP0125,FUL003,2,299,4.41,5.0,215.79,2025-10-26,2025-10-26,5.0,Completed,False,0.0,NaN,4.0,Strong and long-lasting material.,0.35,0,1,598,26.3718,29.90,817.3182

In [9]:
#view the sample data how it looks last 5.
od.tail()

,order_line_id,order_id,date_id,order_date,customer_id,product_id,category,seller_id,seller_rating,location_id,delivery_person_id,payment_id,campaign_id,fulfillment_id,quantity,unit_price,discount_percentage,tax_percentage,shipping_fee,expected_delivery_date,actual_delivery_date,delivery_rating,order_status,return_flag,refund_amount,return_date,customer_rating,review_text,sentiment_score,delivery_delay_days,delivery_sla_days,gross_amount,discount_amount,tax_amount,net_amount
790727,OL00790728,ORD0385002,2025-11-15,2025-11-15,CUST073518,PROD001236,Office Supplies,SELL3351,3.7,LOC0093,DEL06036,PAY008,CAMP0080,FUL003,4,14999,2.83,5.0,215.79,2025-11-16,2025-11-16,4.5,Completed,False,0.00,NaN,4.8,Good quality and long-lasting.,0.39,0,1,59996,1697.8868,2999.80,61513.7032
790728,OL00790729,ORD0231499,2025-09-02,2025-09-02,CUST027946,PROD000245,Home,SELL0889,4.4,LOC0066,DEL00856,PAY002,CAMP0087,FUL003,4,14999,5.60,5.0,215.79,2025-09-03,2025-09-04,3.1,Completed,False,0.00,NaN,3.8,Sturdy build and easy to assemble.,0.89,1,1,59996,3359.7760,2999.80,59851.8140
790729,OL00790730,ORD0274582,2026-02-07,2026-02-07,CUST003703,PROD001217,Office Supplies,SELL1882,2.3,LOC0095,DEL05064,PAY014,CAMP0035,FUL002,5,8999,1.42,5.0,86.64,2026-02-09,2026-02-09,4.7,Returned,True,-86.64,2026-02-11,2.3,Missing parts,-0.21,0,2,44995,638.9290,2249.75,46692.4610
790730,OL00790731,ORD0148799,2025-04-03,2025-04-03,CUST004618,PROD000427,Sports,SELL3383,3.6,LOC0066,DEL06494,PAY012,CAMP0179,FUL001,4,2499,1.19,5.0,46.27,2025-04-08,2025-04-08,4.7,Completed,False,0.00,NaN,4.3,Comfortable and enhances performance.,0.23,0,5,9996,118.9524,499.80,10423.1176
790731,OL00790732,ORD0011904,2025-10-11,2025-10-11,CUST047767,PROD000194,Home,SELL2875,2.3,LOC0105,DEL05710,PAY008,CAMP0017,FUL002,1,999,4.57,5.0,86.64,2025-10-13,2025-10-15,2.1,Returned,True,-86.64,2025-10-17,2.8,Color/finish mismatch,-0.10,2,2,999,45.6543,49.95,1089.9357

In [10]:
#view the sample data how it looks random 5.
od.tail()

,order_line_id,order_id,date_id,order_date,customer_id,product_id,category,seller_id,seller_rating,location_id,delivery_person_id,payment_id,campaign_id,fulfillment_id,quantity,unit_price,discount_percentage,tax_percentage,shipping_fee,expected_delivery_date,actual_delivery_date,delivery_rating,order_status,return_flag,refund_amount,return_date,customer_rating,review_text,sentiment_score,delivery_delay_days,delivery_sla_days,gross_amount,discount_amount,tax_amount,net_amount
790727,OL00790728,ORD0385002,2025-11-15,2025-11-15,CUST073518,PROD001236,Office Supplies,SELL3351,3.7,LOC0093,DEL06036,PAY008,CAMP0080,FUL003,4,14999,2.83,5.0,215.79,2025-11-16,2025-11-16,4.5,Completed,False,0.00,NaN,4.8,Good quality and long-lasting.,0.39,0,1,59996,1697.8868,2999.80,61513.7032
790728,OL00790729,ORD0231499,2025-09-02,2025-09-02,CUST027946,PROD000245,Home,SELL0889,4.4,LOC0066,DEL00856,PAY002,CAMP0087,FUL003,4,14999,5.60,5.0,215.79,2025-09-03,2025-09-04,3.1,Completed,False,0.00,NaN,3.8,Sturdy build and easy to assemble.,0.89,1,1,59996,3359.7760,2999.80,59851.8140
790729,OL00790730,ORD0274582,2026-02-07,2026-02-07,CUST003703,PROD001217,Office Supplies,SELL1882,2.3,LOC0095,DEL05064,PAY014,CAMP0035,FUL002,5,8999,1.42,5.0,86.64,2026-02-09,2026-02-09,4.7,Returned,True,-86.64,2026-02-11,2.3,Missing parts,-0.21,0,2,44995,638.9290,2249.75,46692.4610
790730,OL00790731,ORD0148799,2025-04-03,2025-04-03,CUST004618,PROD000427,Sports,SELL3383,3.6,LOC0066,DEL06494,PAY012,CAMP0179,FUL001,4,2499,1.19,5.0,46.27,2025-04-08,2025-04-08,4.7,Completed,False,0.00,NaN,4.3,Comfortable and enhances performance.,0.23,0,5,9996,118.9524,499.80,10423.1176
790731,OL00790732,ORD0011904,2025-10-11,2025-10-11,CUST047767,PROD000194,Home,SELL2875,2.3,LOC0105,DEL05710,PAY008,CAMP0017,FUL002,1,999,4.57,5.0,86.64,2025-10-13,2025-10-15,2.1,Returned,True,-86.64,2025-10-17,2.8,Color/finish mismatch,-0.10,2,2,999,45.6543,49.95,1089.9357

In [11]:
#check the info of the table.it shows columns and datatype and non_null count 
od.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 790732 entries, 0 to 790731
Data columns (total 35 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   order_line_id           790732 non-null  object
 1   order_id                790732 non-null  object
 2   date_id                 790732 non-null  object
 3   order_date              790732 non-null  object
 4   customer_id             790732 non-null  object
 5   product_id              790732 non-null  object
 6   category                790732 non-null  object
 7   seller_id               790732 non-null  object
 8   seller_rating           751390 non-null  float64
 9   location_id             790732 non-null  object
 10  delivery_person_id      790732 non-null  object
 11  payment_id              790732 non-null  object
 12  campaign_id             790732 non-null  object
 13  fulfillment_id          790732 non-null  object
 14  quantity                790732 non-null  int64
 15  unit_price              790732 non-null  int64
 16  discount_percentage     790732 non-null  float64
 17  tax_percentage          790732 non-null  float64
 18  shipping_fee            790732 non-null  float64
 19  expected_delivery_date  790732 non-null  object
 20  actual_delivery_date    790732 non-null  object
 21  delivery_rating         751390 non-null  float64
 22  order_status            790732 non-null  object
 23  return_flag             790732 non-null  bool
 24  refund_amount           790732 non-null  float64
 25  return_date             103035 non-null  object
 26  customer_rating         751390 non-null  float64
 27  review_text             751390 non-null  object
 28  sentiment_score         790732 non-null  float64
 29  delivery_delay_days     790732 non-null  int64
 30  delivery_sla_days       790732 non-null  int64
 31  gross_amount            790732 non-null  int64
 32  discount_amount         790732 non-null  float64
 33  tax_amount              790732 non-null  float64
 34  net_amount              790732 non-null  float64
dtypes: bool(1), float64(11), int64(5), object(18)
memory usage: 205.9+ MB

In [12]:
#Describe is used to summerize the numeric values in table.
od.describe()

,seller_rating,quantity,unit_price,discount_percentage,tax_percentage,shipping_fee,delivery_rating,refund_amount,customer_rating,sentiment_score,delivery_delay_days,delivery_sla_days,gross_amount,discount_amount,tax_amount,net_amount
count,751390.000000,790732.000000,7.907320e+05,790732.000000,790732.0,790732.000000,751390.000000,790732.000000,751390.000000,790732.000000,790732.000000,790732.000000,7.907320e+05,790732.000000,790732.000000,7.907320e+05
mean,3.934732,3.001877,1.443109e+04,4.998254,5.0,116.332926,3.999883,-15.148007,3.718927,0.379188,0.450298,2.663600,4.322148e+04,2156.610857,2161.074214,4.334228e+04
std,0.911800,1.413882,5.030919e+04,2.886348,0.0,72.308419,0.857078,47.047367,0.910232,0.455638,0.668581,1.698761,1.670267e+05,9589.267398,8351.335561,1.672835e+05
min,1.000000,1.000000,2.000000e+01,0.000000,5.0,46.270000,1.000000,-215.790000,1.000000,-1.000000,0.000000,1.000000,2.000000e+01,0.000000,1.000000,6.536000e+01
25%,3.700000,2.000000,6.990000e+02,2.500000,5.0,46.270000,3.600000,0.000000,3.300000,0.180000,0.000000,1.000000,1.598000e+03,56.780100,79.900000,1.743271e+03
50%,4.100000,3.000000,1.999000e+03,4.990000,5.0,86.640000,4.200000,0.000000,3.800000,0.450000,0.000000,2.000000,5.397000e+03,220.310400,269.850000,5.480861e+03
75%,4.600000,4.000000,8.499000e+03,7.500000,5.0,215.790000,4.600000,0.000000,4.400000,0.730000,1.000000,5.000000,2.249500e+04,974.610000,1124.750000,2.240403e+04
max,5.000000,5.000000,1.150000e+06,10.000000,5.0,215.790000,5.000000,0.000000,5.000000,1.000000,2.000000,5.000000,5.750000e+06,572700.000000,287500.000000,6.031796e+06

In [13]:
#count duplicate records in the table.
od.duplicated().sum()

np.int64(0)

In [14]:
#count missing values or null values count.
od.isna().sum()

order_line_id                  0
order_id                       0
date_id                        0
order_date                     0
customer_id                    0
product_id                     0
category                       0
seller_id                      0
seller_rating              39342
location_id                    0
delivery_person_id             0
payment_id                     0
campaign_id                    0
fulfillment_id                 0
quantity                       0
unit_price                     0
discount_percentage            0
tax_percentage                 0
shipping_fee                   0
expected_delivery_date         0
actual_delivery_date           0
delivery_rating            39342
order_status                   0
return_flag                    0
refund_amount                  0
return_date               687697
customer_rating            39342
review_text                39342
sentiment_score                0
delivery_delay_days            0
delivery_sla_days              0
gross_amount                   0
discount_amount                0
tax_amount                     0
net_amount                     0
dtype: int64

In [15]:
number_of_customers=od['customer_id'].drop_duplicates().count()
print("Number of customers:",number_of_customers)

Number of customers: 90818

In [16]:
number_of_products=od['product_id'].drop_duplicates().count()
print("Number of products:",number_of_products)

Number of products: 1260

In [17]:
number_of_sellers=od['seller_id'].drop_duplicates().count()
print("Number of sellers:",number_of_sellers)

Number of sellers: 4563

In [18]:
number_of_orders=od['order_line_id'].drop_duplicates().count()
print("Number of orders:",number_of_orders)

Number of orders: 790732

In [19]:
number_of_category=od['category'].drop_duplicates().count()
print("Number of category:",number_of_category)

Number of category: 19

In [20]:
number_of_days=od['order_date'].drop_duplicates().count()
print("Number of days:",number_of_days)

Number of days: 366

In [21]:
number_of_locations=od['location_id'].drop_duplicates().count()
print("Number of location:",number_of_locations)

Number of location: 113

In [22]:
number_of_delivery_persons=od['delivery_person_id'].drop_duplicates().count()
print("Number of delivery_persons:",number_of_delivery_persons)

Number of delivery_persons: 7421

In [23]:
number_of_campaigns=od['campaign_id'].drop_duplicates().count()
print("Number of campaigns:",number_of_campaigns)

Number of campaigns: 202

## Create a Data Dictionary

-  Order_Line_Id Object  Unique order identifier
-  Date_Id Date  Date reference
-  Order_Date Date  Date of order
-  Customer_Id Object  Customer reference
-  Product_Id Object  Product reference
-  Category Object  Category of product
-  Seller_Id Object  Seller reference
-  Seller_Rating Float64  Seller rating
-  Location_Id Object  Location reference
-  Delivery_Person_Id Object  Delivery reference
-  Payment_Id Object  Payment reference
-  Campaign_Id Object  Campaign reference
-  Fulfillment_Id Object  Fulfillment reference
-  Quantity Int64  Number of items ordered
-  Unit_Price Int64  Price of each item
-  Discount_Percentage Float64  Discount percentage
-  Tax_Percentage Float64  Tax percentage
-  Shipping_Fee Float64  Shipping fee 
-  Expected_Delivery_Date Date   Expected Delivery Date 
-  Actual_Delivery_Date Date   Actual Delivery Date 
-  Delivery_Rating Float64  Rating of delivery
-  Order_Status Object  Status of order
-  Return_Flag Bool  Return status
-  Refund_Amount Float64   Refund_Amount
-  Return_Date Date   Return_Date
-  Customer_Rating Float64  Rating of  customer
-  Review_Text Object   Review of customer
-  Sentiment_Score Float64   Sentiment_Score  of customer
-  Delivery_Delay_Days Int64  Number of delivery days
-  Gross_Amount Int64   Gross_Amount (quantity*price)
-  Discount_Amount Float64   Discount_Amount
-  Tax_Amount Float64   Tax_Amount
-  Net_Amount Float64  Price of the product customer paid

## Data Quality Assessment
- Instead of jumping into cleaning, create a checklist.
- Missing Values	Yes
- Duplicate Rows	No
- Incorrect Data Types	Yes
- Negative Quantities	Yes
- Invalid Categories	No

In [32]:
#null_values_check
null_values_check=od.isna().sum()
print(null_values_check)

order_line_id                  0
order_id                       0
date_id                        0
order_date                     0
customer_id                    0
product_id                     0
category                       0
seller_id                      0
seller_rating              39342
location_id                    0
delivery_person_id             0
payment_id                     0
campaign_id                    0
fulfillment_id                 0
quantity                       0
unit_price                     0
discount_percentage            0
tax_percentage                 0
shipping_fee                   0
expected_delivery_date         0
actual_delivery_date           0
delivery_rating            39342
order_status                   0
return_flag                    0
refund_amount                  0
return_date               687697
customer_rating            39342
review_text                39342
sentiment_score                0
delivery_delay_days            0
delivery_sla_days              0
gross_amount                   0
discount_amount                0
tax_amount                     0
net_amount                     0
dtype: int64

In [33]:
#duplicate_values_check

duplicate_values_check=od.duplicated().sum()
print(duplicate_values_check)

0

In [34]:
# data_type_check

data_type_check=od.dtypes
print(data_type_check)

order_line_id              object
order_id                   object
date_id                    object
order_date                 object
customer_id                object
product_id                 object
category                   object
seller_id                  object
seller_rating             float64
location_id                object
delivery_person_id         object
payment_id                 object
campaign_id                object
fulfillment_id             object
quantity                    int64
unit_price                  int64
discount_percentage       float64
tax_percentage            float64
shipping_fee              float64
expected_delivery_date     object
actual_delivery_date       object
delivery_rating           float64
order_status               object
return_flag                  bool
refund_amount             float64
return_date                object
customer_rating           float64
review_text                object
sentiment_score           float64
delivery_delay_days         int64
delivery_sla_days           int64
gross_amount                int64
discount_amount           float64
tax_amount                float64
net_amount                float64
dtype: object

## Cleaning
1. Remove duplicate records.
2. Convert date columns.
3. Handle missing values.
4. Standardize category names.
5. Remove impossible values.
6. Detect outliers.
7. Merge related datasets.
8. Save cleaned dataset.

In [38]:
#Remove duplicate records

od=od.drop_duplicates()

In [39]:
od.head()

,order_line_id,order_id,date_id,order_date,customer_id,product_id,category,seller_id,seller_rating,location_id,delivery_person_id,payment_id,campaign_id,fulfillment_id,quantity,unit_price,discount_percentage,tax_percentage,shipping_fee,expected_delivery_date,actual_delivery_date,delivery_rating,order_status,return_flag,refund_amount,return_date,customer_rating,review_text,sentiment_score,delivery_delay_days,delivery_sla_days,gross_amount,discount_amount,tax_amount,net_amount
0,OL00000001,ORD0210788,2026-02-20,2026-02-20,CUST009513,PROD000763,Baby,SELL2379,4.6,LOC0010,DEL01094,PAY005,CAMP0098,FUL002,2,19999,9.66,5.0,86.64,2026-02-22,2026-02-22,4.5,Completed,False,0.0,NaN,4.4,Very soft and baby-friendly material.,0.84,0,2,39998,3863.8068,1999.90,38220.7332
1,OL00000002,ORD0248321,2025-12-02,2025-12-02,CUST003412,PROD000142,Clothing,SELL2964,4.0,LOC0053,DEL01927,PAY004,CAMP0068,FUL003,4,2499,7.04,5.0,215.79,2025-12-03,2025-12-04,3.9,Completed,False,0.0,NaN,4.3,Stitching is neat and well-finished.,0.66,1,1,9996,703.7184,499.80,10007.8716
2,OL00000003,ORD0377603,2025-04-03,2025-04-03,CUST065509,PROD001194,Gaming,SELL2485,3.9,LOC0095,DEL00300,PAY009,CAMP0103,FUL002,5,89999,5.75,5.0,86.64,2025-04-05,2025-04-06,3.9,Completed,False,0.0,NaN,4.6,Highly enjoyable and worth it.,0.44,1,2,449995,25874.7125,22499.75,446706.6775
3,OL00000004,ORD0019414,2025-06-01,2025-06-01,CUST070677,PROD000221,Home,SELL4121,4.0,LOC0038,DEL02152,PAY004,CAMP0001,FUL002,3,1499,0.61,5.0,86.64,2025-06-03,2025-06-03,4.0,Completed,False,0.0,NaN,4.6,Fits perfectly in my space.,0.28,0,2,4497,27.4317,224.85,4781.0583
4,OL00000005,ORD0157859,2025-10-25,2025-10-25,CUST017845,PROD000806,Pets,SELL3183,4.5,LOC0109,DEL03896,PAY012,CAMP0125,FUL003,2,299,4.41,5.0,215.79,2025-10-26,2025-10-26,5.0,Completed,False,0.0,NaN,4.0,Strong and long-lasting material.,0.35,0,1,598,26.3718,29.90,817.3182

In [36]:
od.columns

Index(['order_line_id', 'order_id', 'date_id', 'order_date', 'customer_id',
       'product_id', 'category', 'seller_id', 'seller_rating', 'location_id',
       'delivery_person_id', 'payment_id', 'campaign_id', 'fulfillment_id',
       'quantity', 'unit_price', 'discount_percentage', 'tax_percentage',
       'shipping_fee', 'expected_delivery_date', 'actual_delivery_date',
       'delivery_rating', 'order_status', 'return_flag', 'refund_amount',
       'return_date', 'customer_rating', 'review_text', 'sentiment_score',
       'delivery_delay_days', 'delivery_sla_days', 'gross_amount',
       'discount_amount', 'tax_amount', 'net_amount'],
      dtype='object')

In [ ]:

od[['date_id','order_date','expected_delivery_date', 'actual_delivery_date','return_date']]

,date_id,order_date,expected_delivery_date,actual_delivery_date,return_date
0,2026-02-20,2026-02-20,2026-02-22,2026-02-22,NaN
1,2025-12-02,2025-12-02,2025-12-03,2025-12-04,NaN
2,2025-04-03,2025-04-03,2025-04-05,2025-04-06,NaN
3,2025-06-01,2025-06-01,2025-06-03,2025-06-03,NaN
4,2025-10-25,2025-10-25,2025-10-26,2025-10-26,NaN
...,...,...,...,...,...
790727,2025-11-15,2025-11-15,2025-11-16,2025-11-16,NaN
790728,2025-09-02,2025-09-02,2025-09-03,2025-09-04,NaN
790729,2026-02-07,2026-02-07,2026-02-09,2026-02-09,2026-02-11
790730,2025-04-03,2025-04-03,2025-04-08,2025-04-08,NaN
790731,2025-10-11,2025-10-11,2025-10-13,2025-10-15,2025-10-17

In [ ]:
#change the data_type

od[['date_id', 'order_date', 'expected_delivery_date',
    'actual_delivery_date', 'return_date']] = (
    od[['date_id', 'order_date', 'expected_delivery_date',
        'actual_delivery_date', 'return_date']]
    .apply(pd.to_datetime)
)

In [ ]:
od.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 790732 entries, 0 to 790731
Data columns (total 35 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   order_line_id           790732 non-null  object
 1   order_id                790732 non-null  object
 2   date_id                 790732 non-null  datetime64[ns]
 3   order_date              790732 non-null  datetime64[ns]
 4   customer_id             790732 non-null  object
 5   product_id              790732 non-null  object
 6   category                790732 non-null  object
 7   seller_id               790732 non-null  object
 8   seller_rating           751390 non-null  float64
 9   location_id             790732 non-null  object
 10  delivery_person_id      790732 non-null  object
 11  payment_id              790732 non-null  object
 12  campaign_id             790732 non-null  object
 13  fulfillment_id          790732 non-null  object
 14  quantity                790732 non-null  int64
 15  unit_price              790732 non-null  int64
 16  discount_percentage     790732 non-null  float64
 17  tax_percentage          790732 non-null  float64
 18  shipping_fee            790732 non-null  float64
 19  expected_delivery_date  790732 non-null  datetime64[ns]
 20  actual_delivery_date    790732 non-null  datetime64[ns]
 21  delivery_rating         751390 non-null  float64
 22  order_status            790732 non-null  object
 23  return_flag             790732 non-null  bool
 24  refund_amount           790732 non-null  float64
 25  return_date             103035 non-null  datetime64[ns]
 26  customer_rating         751390 non-null  float64
 27  review_text             751390 non-null  object
 28  sentiment_score         790732 non-null  float64
 29  delivery_delay_days     790732 non-null  int64
 30  delivery_sla_days       790732 non-null  int64
 31  gross_amount            790732 non-null  int64
 32  discount_amount         790732 non-null  float64
 33  tax_amount              790732 non-null  float64
 34  net_amount              790732 non-null  float64
dtypes: bool(1), datetime64[ns](5), float64(11), int64(5), object(13)
memory usage: 205.9+ MB

In [52]:
od.head()

,order_line_id,order_id,date_id,order_date,customer_id,product_id,category,seller_id,seller_rating,location_id,delivery_person_id,payment_id,campaign_id,fulfillment_id,quantity,unit_price,discount_percentage,tax_percentage,shipping_fee,expected_delivery_date,actual_delivery_date,delivery_rating,order_status,return_flag,refund_amount,return_date,customer_rating,review_text,sentiment_score,delivery_delay_days,delivery_sla_days,gross_amount,discount_amount,tax_amount,net_amount
0,OL00000001,ORD0210788,2026-02-20,2026-02-20,CUST009513,PROD000763,Baby,SELL2379,4.6,LOC0010,DEL01094,PAY005,CAMP0098,FUL002,2,19999,9.66,5.0,86.64,2026-02-22,2026-02-22,4.5,Completed,False,0.0,NaN,4.4,Very soft and baby-friendly material.,0.84,0,2,39998,3863.8068,1999.90,38220.7332
1,OL00000002,ORD0248321,2025-12-02,2025-12-02,CUST003412,PROD000142,Clothing,SELL2964,4.0,LOC0053,DEL01927,PAY004,CAMP0068,FUL003,4,2499,7.04,5.0,215.79,2025-12-03,2025-12-04,3.9,Completed,False,0.0,NaN,4.3,Stitching is neat and well-finished.,0.66,1,1,9996,703.7184,499.80,10007.8716
2,OL00000003,ORD0377603,2025-04-03,2025-04-03,CUST065509,PROD001194,Gaming,SELL2485,3.9,LOC0095,DEL00300,PAY009,CAMP0103,FUL002,5,89999,5.75,5.0,86.64,2025-04-05,2025-04-06,3.9,Completed,False,0.0,NaN,4.6,Highly enjoyable and worth it.,0.44,1,2,449995,25874.7125,22499.75,446706.6775
3,OL00000004,ORD0019414,2025-06-01,2025-06-01,CUST070677,PROD000221,Home,SELL4121,4.0,LOC0038,DEL02152,PAY004,CAMP0001,FUL002,3,1499,0.61,5.0,86.64,2025-06-03,2025-06-03,4.0,Completed,False,0.0,NaN,4.6,Fits perfectly in my space.,0.28,0,2,4497,27.4317,224.85,4781.0583
4,OL00000005,ORD0157859,2025-10-25,2025-10-25,CUST017845,PROD000806,Pets,SELL3183,4.5,LOC0109,DEL03896,PAY012,CAMP0125,FUL003,2,299,4.41,5.0,215.79,2025-10-26,2025-10-26,5.0,Completed,False,0.0,NaN,4.0,Strong and long-lasting material.,0.35,0,1,598,26.3718,29.90,817.3182

In [59]:
#check null or missing values
od.isna().sum()

order_line_id                  0
order_id                       0
date_id                        0
order_date                     0
customer_id                    0
product_id                     0
category                       0
seller_id                      0
seller_rating              39342
location_id                    0
delivery_person_id             0
payment_id                     0
campaign_id                    0
fulfillment_id                 0
quantity                       0
unit_price                     0
discount_percentage            0
tax_percentage                 0
shipping_fee                   0
expected_delivery_date         0
actual_delivery_date           0
delivery_rating            39342
order_status                   0
return_flag                    0
refund_amount                  0
return_date               687697
customer_rating            39342
review_text                39342
sentiment_score                0
delivery_delay_days            0
delivery_sla_days              0
gross_amount                   0
discount_amount                0
tax_amount                     0
net_amount                     0
dtype: int64

# Handling Null values

In [62]:
od[['seller_rating','delivery_rating','return_date','customer_rating','review_text']]

,seller_rating,delivery_rating,return_date,customer_rating,review_text
0,4.6,4.5,NaT,4.4,Very soft and baby-friendly material.
1,4.0,3.9,NaT,4.3,Stitching is neat and well-finished.
2,3.9,3.9,NaT,4.6,Highly enjoyable and worth it.
3,4.0,4.0,NaT,4.6,Fits perfectly in my space.
4,4.5,5.0,NaT,4.0,Strong and long-lasting material.
...,...,...,...,...,...
790727,3.7,4.5,NaT,4.8,Good quality and long-lasting.
790728,4.4,3.1,NaT,3.8,Sturdy build and easy to assemble.
790729,2.3,4.7,2026-02-11,2.3,Missing parts
790730,3.6,4.7,NaT,4.3,Comfortable and enhances performance.
790731,2.3,2.1,2025-10-17,2.8,Color/finish mismatch

In [ ]:
#filling null values with no comments
od['review_text']=od['review_text'].fillna("No Comments")

In [ ]:
# rating columns is filled with mean
rating_cols = ['seller_rating', 'delivery_rating', 'customer_rating']

for col in rating_cols:
    od[col] = od[col].fillna(od[col].mean())

In [71]:
od['return_date']=od['return_date'].fillna(np.nan)

In [74]:
od.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 790732 entries, 0 to 790731
Data columns (total 35 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   order_line_id           790732 non-null  object
 1   order_id                790732 non-null  object
 2   date_id                 790732 non-null  datetime64[ns]
 3   order_date              790732 non-null  datetime64[ns]
 4   customer_id             790732 non-null  object
 5   product_id              790732 non-null  object
 6   category                790732 non-null  object
 7   seller_id               790732 non-null  object
 8   seller_rating           790732 non-null  float64
 9   location_id             790732 non-null  object
 10  delivery_person_id      790732 non-null  object
 11  payment_id              790732 non-null  object
 12  campaign_id             790732 non-null  object
 13  fulfillment_id          790732 non-null  object
 14  quantity                790732 non-null  int64
 15  unit_price              790732 non-null  int64
 16  discount_percentage     790732 non-null  float64
 17  tax_percentage          790732 non-null  float64
 18  shipping_fee            790732 non-null  float64
 19  expected_delivery_date  790732 non-null  datetime64[ns]
 20  actual_delivery_date    790732 non-null  datetime64[ns]
 21  delivery_rating         790732 non-null  float64
 22  order_status            790732 non-null  object
 23  return_flag             790732 non-null  bool
 24  refund_amount           790732 non-null  float64
 25  return_date             790732 non-null  datetime64[ns]
 26  customer_rating         790732 non-null  float64
 27  review_text             790732 non-null  object
 28  sentiment_score         790732 non-null  float64
 29  delivery_delay_days     790732 non-null  int64
 30  delivery_sla_days       790732 non-null  int64
 31  gross_amount            790732 non-null  int64
 32  discount_amount         790732 non-null  float64
 33  tax_amount              790732 non-null  float64
 34  net_amount              790732 non-null  float64
dtypes: bool(1), datetime64[ns](5), float64(11), int64(5), object(13)
memory usage: 205.9+ MB

In [67]:
od.isna().sum()

order_line_id                  0
order_id                       0
date_id                        0
order_date                     0
customer_id                    0
product_id                     0
category                       0
seller_id                      0
seller_rating                  0
location_id                    0
delivery_person_id             0
payment_id                     0
campaign_id                    0
fulfillment_id                 0
quantity                       0
unit_price                     0
discount_percentage            0
tax_percentage                 0
shipping_fee                   0
expected_delivery_date         0
actual_delivery_date           0
delivery_rating                0
order_status                   0
return_flag                    0
refund_amount                  0
return_date               687697
customer_rating                0
review_text                    0
sentiment_score                0
delivery_delay_days            0
delivery_sla_days              0
gross_amount                   0
discount_amount                0
tax_amount                     0
net_amount                     0
dtype: int64

In [75]:
od.head()

,order_line_id,order_id,date_id,order_date,customer_id,product_id,category,seller_id,seller_rating,location_id,delivery_person_id,payment_id,campaign_id,fulfillment_id,quantity,unit_price,discount_percentage,tax_percentage,shipping_fee,expected_delivery_date,actual_delivery_date,delivery_rating,order_status,return_flag,refund_amount,return_date,customer_rating,review_text,sentiment_score,delivery_delay_days,delivery_sla_days,gross_amount,discount_amount,tax_amount,net_amount
0,OL00000001,ORD0210788,2026-02-20,2026-02-20,CUST009513,PROD000763,Baby,SELL2379,4.6,LOC0010,DEL01094,PAY005,CAMP0098,FUL002,2,19999,9.66,5.0,86.64,2026-02-22,2026-02-22,4.5,Completed,False,0.0,1970-01-01,4.4,Very soft and baby-friendly material.,0.84,0,2,39998,3863.8068,1999.90,38220.7332
1,OL00000002,ORD0248321,2025-12-02,2025-12-02,CUST003412,PROD000142,Clothing,SELL2964,4.0,LOC0053,DEL01927,PAY004,CAMP0068,FUL003,4,2499,7.04,5.0,215.79,2025-12-03,2025-12-04,3.9,Completed,False,0.0,1970-01-01,4.3,Stitching is neat and well-finished.,0.66,1,1,9996,703.7184,499.80,10007.8716
2,OL00000003,ORD0377603,2025-04-03,2025-04-03,CUST065509,PROD001194,Gaming,SELL2485,3.9,LOC0095,DEL00300,PAY009,CAMP0103,FUL002,5,89999,5.75,5.0,86.64,2025-04-05,2025-04-06,3.9,Completed,False,0.0,1970-01-01,4.6,Highly enjoyable and worth it.,0.44,1,2,449995,25874.7125,22499.75,446706.6775
3,OL00000004,ORD0019414,2025-06-01,2025-06-01,CUST070677,PROD000221,Home,SELL4121,4.0,LOC0038,DEL02152,PAY004,CAMP0001,FUL002,3,1499,0.61,5.0,86.64,2025-06-03,2025-06-03,4.0,Completed,False,0.0,1970-01-01,4.6,Fits perfectly in my space.,0.28,0,2,4497,27.4317,224.85,4781.0583
4,OL00000005,ORD0157859,2025-10-25,2025-10-25,CUST017845,PROD000806,Pets,SELL3183,4.5,LOC0109,DEL03896,PAY012,CAMP0125,FUL003,2,299,4.41,5.0,215.79,2025-10-26,2025-10-26,5.0,Completed,False,0.0,1970-01-01,4.0,Strong and long-lasting material.,0.35,0,1,598,26.3718,29.90,817.3182

In [76]:
od['category'].unique()

array(['Baby', 'Clothing', 'Gaming', 'Home', 'Pets', 'Electronics',
       'Footwear', 'Groceries', 'Books', 'Beauty', 'Sports',
       'Bags & Luggage', 'Automotive', 'Office Supplies',
       'Music & Instruments', 'Stationery', 'Jewellery', 'Toys', 'Health'],
      dtype=object)

In [77]:
od['order_status'].unique()

array(['Completed', 'Returned', 'Cancelled'], dtype=object)

In [78]:
od['return_flag'].unique()

array([False,  True])

# Detect_outliers using boxplot

# 6. Feature Engineering
### Create useful columns such as:
- Profit 
- Profit Margin 
- Delivery Days 
- Order Month 
- Order Quarter 
- Order Year 
- Shipping Delay